// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// gmpr
NumericVector gmpr(IntegerMatrix x, int min_ct, int intersect_no);
RcppExport SEXP _GMPR_gmpr(SEXP xSEXP, SEXP min_ctSEXP, SEXP intersect_noSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerMatrix >::type x(xSEXP);
    Rcpp::traits::input_parameter< int >::type min_ct(min_ctSEXP);
    Rcpp::traits::input_parameter< int >::type intersect_no(intersect_noSEXP);
    rcpp_result_gen = Rcpp::wrap(gmpr(x, min_ct, intersect_no));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_GMPR_gmpr", (DL_FUNC) &_GMPR_gmpr, 3},
    {NULL, NULL, 0}
};

RcppExport void R_init_GMPR(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
