# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

gmpr <- function(x, min_ct, intersect_no) {
    .Call('_GMPR_gmpr', PACKAGE = 'GMPR', x, min_ct, intersect_no)
}

